import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,BookOpen,Download,RefreshCw,Satellite,Trash2,Plus,Check,AlertCircle} from 'lucide-react';
import {dataLayers,fetchCatalog,PAGE_SIZE,readNotebook,notebookReport,type LayerId,type CatalogPage,type LunarProduct,type ResearchEntry} from './lunarApi';
import './lunar.css';
const KEY='aqua-lunar.research.v1';
function initial(){try{return readNotebook(localStorage.getItem(KEY))}catch{return []}}
function date(value:string){return new Date(value).toLocaleString('pt-BR')}
export default function LunarExplorer(){
 const [layerId,setLayerId]=useState<LayerId>('thermal');
 const [page,setPage]=useState<CatalogPage|null>(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState('');
 const [entries,setEntries]=useState<ResearchEntry[]>(initial),[message,setMessage]=useState('');
 const request=useRef<AbortController|null>(null);
 const layer=dataLayers.find(x=>x.id===layerId)!;
 useEffect(()=>()=>request.current?.abort(),[]);
 async function search(offset=0,refresh=false){
  request.current?.abort();const controller=new AbortController();request.current=controller;
  setLoading(true);setError('');setPage(null);
  try{const result=await fetchCatalog(layerId,offset,controller.signal,refresh);if(!controller.signal.aborted)setPage(result)}
  catch(err){if(!controller.signal.aborted)setError(err instanceof Error&&err.name!=='TypeError'&&err.name!=='TimeoutError'?err.message:'Não foi possível acessar o ODE. Verifique a conexão ou tente novamente. O simulador continua disponível.')}
  finally{if(!controller.signal.aborted)setLoading(false)}
 }
 function changeLayer(id:LayerId){request.current?.abort();setLayerId(id);setPage(null);setError('');setLoading(false)}
 function persist(next:ResearchEntry[]){setEntries(next);try{localStorage.setItem(KEY,JSON.stringify(next));setMessage('Caderno salvo neste navegador.')}catch{setMessage('Armazenamento indisponível. Exporte o caderno antes de fechar a página.')}}
 function add(product:LunarProduct){if(!page||entries.some(x=>x.product.id===product.id))return;if(entries.length>=12){setMessage('O caderno comporta 12 registros. Exporte ou remova um para continuar.');return;}persist([...entries,{product,queryUrl:page.queryUrl,fetchedAt:page.fetchedAt,layerId,note:''}])}
 function exportNotes(){const url=URL.createObjectURL(new Blob([notebookReport(entries)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aqua-lunar-pesquisa.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="lunar-explorer"><div className="api-banner"><Satellite size={24}/><div><strong>NASA PDS · ODE</strong><p>Consulte produtos científicos reais. Guarde registros e escreva o que cada um permite concluir.</p></div><span>API pública · sem chave</span></div>
 <div className="layer-tabs" role="group" aria-label="Camadas de pesquisa">{dataLayers.map(x=><button key={x.id} aria-pressed={layerId===x.id} className={layerId===x.id?'selected':''} onClick={()=>changeLayer(x.id)}><span>{x.instrument}</span><strong>{x.name}</strong></button>)}</div>
 <div className="query-panel"><div><span className="eyebrow">{layer.instrument} · {layer.pt}</span><h2>{layer.question}</h2><p>{layer.note}</p><small>{layer.scope}. Consulta ao acervo completo deste tipo, sem filtro de local ou data.</small></div><button className="button primary" disabled={loading} onClick={()=>search(0,true)}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Consultando ODE...':'Consultar catálogo'}</button></div>
 {layerId==='thermal'&&<div className="version-note"><BookOpen size={18}/><p>Nos rótulos PRP consultados, o recurso científico está na versão 2. A versão 1.0 do rótulo PDS4 é outro campo. A profundidade de estabilidade é modelada e não é uma medição de gelo. <a href="https://pds-geosciences.wustl.edu/lro/urn-nasa-pds-lro_diviner_derived1/data_derived_prp/dlre_prp_south.xml" target="_blank" rel="noreferrer">Ver rótulo do polo sul</a>.</p></div>}
 <div aria-live="polite" className="query-status">{loading?'Buscando registros diretamente no serviço científico...':page?`${page.products.length} registros nesta página · consultado em ${date(page.fetchedAt)}`:!error?'Selecione uma camada e consulte o catálogo para começar.':''}</div>
 {error&&<div className="api-error" role="alert"><AlertCircle size={20}/><p>{error}</p><button className="button outline" onClick={()=>search(0,true)}>Tentar novamente</button></div>}
 {page&&<><div className="catalog-meta"><a href={page.queryUrl} target="_blank" rel="noreferrer">Consulta original em JSON <ArrowUpRight size={14}/></a><span>Metadados recebidos do ODE, sem análise dos arquivos científicos</span></div><div className="product-grid">{page.products.map(p=><article className="product-card" key={p.id}><div className="product-kicker"><span>{p.instrument} / {p.productType}</span><span>REGISTRO DO ACERVO</span></div><h3>{p.title}</h3><dl><div><dt>Identificador</dt><dd>{p.pdsId}</dd></div><div><dt>Conjunto de dados</dt><dd>{p.dataset}</dd></div>{p.createdAt&&<div><dt>Criação do produto, como informada</dt><dd>{p.createdAt.replace('T',' ')}</dd></div>}{p.labelVersion&&<div><dt>Versão do rótulo no catálogo</dt><dd>{p.labelVersion}</dd></div>}</dl><div className="product-links"><a href={p.productUrl} target="_blank" rel="noreferrer">Registro <ArrowUpRight size={13}/></a>{p.labelUrl&&<a href={p.labelUrl} target="_blank" rel="noreferrer">Rótulo original <ArrowUpRight size={13}/></a>}<a href={p.filesUrl} target="_blank" rel="noreferrer">Arquivos <ArrowUpRight size={13}/></a></div><button className="button outline full" disabled={entries.some(x=>x.product.id===p.id)} onClick={()=>add(p)}>{entries.some(x=>x.product.id===p.id)?<><Check size={15}/> No caderno</>:<><Plus size={15}/> Guardar para investigar</>}</button></article>)}</div>{page.products.length===0&&<div className="empty"><h3>Nenhum registro nesta página</h3><p>Isso não demonstra ausência do recurso. Volte à primeira página ou consulte outro tipo de produto.</p></div>}<div className="catalog-pages"><button className="button outline" disabled={!page.offset||loading} onClick={()=>search(Math.max(0,page.offset-PAGE_SIZE))}>Página anterior</button><span>Página {page.offset/PAGE_SIZE+1}</span><button className="button outline" disabled={page.products.length<PAGE_SIZE||page.offset>=600||loading} onClick={()=>search(page.offset+PAGE_SIZE)}>Próxima página</button></div></>}
 <section className="research-notebook"><div className="section-heading"><div><span className="eyebrow">DA CONSULTA AO ARGUMENTO</span><h2>Seu caderno de pesquisa</h2></div><button className="button outline" disabled={!entries.length} onClick={exportNotes}><Download size={16}/> Exportar caderno</button></div><p className="notebook-intro">{entries.length}/12 registros. Ler um metadado não é interpretar uma medição. Anote o que verificou, a escala, as incertezas e o que falta investigar.</p><div role="status" className="notebook-message">{message}</div>{!entries.length?<div className="notebook-empty"><BookOpen size={25}/><p>Guarde um registro do catálogo para começar. Suas anotações ficam neste navegador.</p></div>:entries.map(entry=><article className="note-card" key={entry.product.id}><div><span className="eyebrow">{entry.product.instrument} · {entry.product.productType}</span><h3>{entry.product.pdsId}</h3><a href={entry.product.productUrl} target="_blank" rel="noreferrer">Reabrir registro <ArrowUpRight size={13}/></a><small>Consultado em {date(entry.fetchedAt)}</small></div><label>Minha interpretação e seus limites<textarea maxLength={1200} value={entry.note} placeholder="O que o produto mostra? Qual versão e escala? O que ele não permite concluir?" onChange={e=>persist(entries.map(x=>x.product.id===entry.product.id?{...x,note:e.target.value}:x))}/></label><button className="icon-btn" aria-label={`Remover ${entry.product.pdsId}`} onClick={()=>persist(entries.filter(x=>x.product.id!==entry.product.id))}><Trash2 size={17}/></button></article>)}</section>
 <div className="version-note"><AlertCircle size={18}/><p>Contagem de registros não é quantidade de gelo. Esta integração consulta metadados e links, sem baixar tabelas volumosas ou converter valores em teor de água. <a href={layer.doc} target="_blank" rel="noreferrer">Leia a documentação do instrumento</a>.</p></div></section>;
}
