import {useEffect,useMemo,useState} from 'react';
import {ArrowDownToLine,CheckCircle2,ClipboardCheck,FileText,Plus,Trash2} from 'lucide-react';
import {calculate,type Scenario,uses} from './model';
import './mission.css';

const KEY='aqua-lunar.mission.v1';
type Evidence={instrument:string;product:string;finding:string;limit:string;url:string};
type Draft={mission:string;region:string;extraction:string;utilization:string;decisionLog:string;evidence:Evidence[]};
const blankEvidence=():Evidence=>({instrument:'',product:'',finding:'',limit:'',url:''});
const initial:Draft={mission:'',region:'',extraction:'',utilization:'',decisionLog:'',evidence:[blankEvidence(),blankEvidence(),blankEvidence()]};
function load():Draft{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x||typeof x!=='object'||!Array.isArray(x.evidence))return initial;return {mission:typeof x.mission==='string'?x.mission:'',region:typeof x.region==='string'?x.region:'',extraction:typeof x.extraction==='string'?x.extraction:'',utilization:typeof x.utilization==='string'?x.utilization:'',decisionLog:typeof x.decisionLog==='string'?x.decisionLog:'',evidence:x.evidence.slice(0,6).map((e:unknown)=>{const v=e&&typeof e==='object'?e as Record<string,unknown>:{};return {instrument:typeof v.instrument==='string'?v.instrument:'',product:typeof v.product==='string'?v.product:'',finding:typeof v.finding==='string'?v.finding:'',limit:typeof v.limit==='string'?v.limit:'',url:typeof v.url==='string'?v.url:''}})}}catch{return initial}}
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function MissionPlanner({scenario}:{scenario:Scenario}){
 const [draft,setDraft]=useState<Draft>(load);const result=useMemo(()=>calculate(scenario),[scenario]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(draft))}catch{}},[draft]);
 const update=(key:Exclude<keyof Draft,'evidence'>,value:string)=>setDraft(old=>({...old,[key]:value}));
 const evidenceOk=draft.evidence.filter(x=>x.instrument.trim()&&x.product.trim()&&x.finding.trim()&&x.limit.trim()&&x.url.trim()).length;
 const required=[draft.mission.trim(),draft.region.trim(),draft.extraction.trim(),draft.utilization.trim(),draft.decisionLog.trim(),evidenceOk>=3];
 const complete=required.filter(Boolean).length;
 function report(){const decision=`${draft.mission||'[nome da missão]'}: extrair água na região ${draft.region||'[região a definir]'} para ${uses[scenario.use].name.toLocaleLowerCase()}.`;return `# Planejamento de missão: ${draft.mission||'sem nome'}\n\n## 1. Decisão\n\n${decision}\n\n## 2. Evidências\n\n${draft.evidence.map((x,i)=>`### Evidência ${i+1}\n- Instrumento ou camada: ${x.instrument||'[preencher]'}\n- Produto e versão: ${x.product||'[preencher]'}\n- O que mostra: ${x.finding||'[preencher]'}\n- Limite ou incerteza: ${x.limit||'[preencher]'}\n- Fonte primária: ${x.url||'[preencher]'}\n`).join('\n')}\n## 3. Extração\n\n${draft.extraction||'[preencher]'}\n\nPremissas atuais do laboratório: ${scenario.concentration}% de gelo em massa, ${scenario.depth} cm de cobertura, ${scenario.recovery}% de captura e ${scenario.separation}% de recuperação na separação. Para ${scenario.target} kg de água após separação, o modelo calcula ${result.feed.toLocaleString('pt-BR',{maximumFractionDigits:0})} kg de alimentação e ${result.energy.toLocaleString('pt-BR',{maximumFractionDigits:0})} kWh de energia parcial. São hipóteses, não medições da região.\n\n## 4. Utilização\n\n${draft.utilization||'[preencher]'}\n\n## 5. Processo de decisão e ferramentas\n\n${draft.decisionLog||'[preencher]'}\n\n## Checklist\n\n- [${draft.mission&&draft.region?'x':' '}] Decisão com missão, recurso e região\n- [${evidenceOk>=3?'x':' '}] Três evidências completas, cada uma com limite\n- [${draft.extraction?'x':' '}] Extração explicada\n- [${draft.utilization?'x':' '}] Utilização explicada\n- [${draft.decisionLog?'x':' '}] Registro de processo, ferramentas e verificação\n\nEste arquivo é um rascunho para revisão. O briefing, os produtos de origem e as interpretações da equipe prevalecem.\n`;}
 return <section className="mission-planner"><div className="planner-head"><div><span className="eyebrow"><ClipboardCheck size={15}/> ROTEIRO PARA A ENTREGA</span><h2>Monte o argumento da missão</h2><p>O laboratório calcula cenários. Aqui a equipe registra a decisão, as evidências e o que foi verificado antes de transformar o material em slides.</p></div><button className="button outline" onClick={()=>download(report(),'aqua-lunar-missao.md')}><ArrowDownToLine size={16}/> Exportar rascunho</button></div>
 <div className="mission-progress" aria-label={`${complete} de 6 itens completos`}><span>{complete}/6 itens para revisar</span><i><b style={{width:`${complete/6*100}%`}}/></i></div>
 <article className="mission-card"><span className="mission-number">01</span><div><h3>Decisão</h3><p>Uma frase com nome, recurso e região.</p></div><label>Nome da missão<input value={draft.mission} maxLength={90} placeholder="Ex.: Aurora Sul" onChange={e=>update('mission',e.target.value)}/></label><label>Região lunar<input value={draft.region} maxLength={120} placeholder="Ex.: área de investigação no polo sul" onChange={e=>update('region',e.target.value)}/></label><output>{draft.mission||'[missão]'}: extrair água em {draft.region||'[região]'} para {uses[scenario.use].short.toLocaleLowerCase()}.</output></article>
 <article className="mission-card evidence-card"><span className="mission-number">02</span><div><h3>Evidências</h3><p>Três ou mais produtos complementares. Registre o limite de cada um.</p></div>{draft.evidence.map((e,index)=><fieldset key={index}><legend>Evidência {index+1}</legend><label>Instrumento ou camada<input value={e.instrument} maxLength={100} placeholder="Ex.: Diviner PRP" onChange={event=>setDraft(old=>({...old,evidence:old.evidence.map((x,i)=>i===index?{...x,instrument:event.target.value}:x)}))}/></label><label>Produto e versão<input value={e.product} maxLength={180} placeholder="Produto, versão e área consultada" onChange={event=>setDraft(old=>({...old,evidence:old.evidence.map((x,i)=>i===index?{...x,product:event.target.value}:x)}))}/></label><label>O que mostra<textarea value={e.finding} maxLength={650} placeholder="Descreva a observação sem extrapolar além do produto." onChange={event=>setDraft(old=>({...old,evidence:old.evidence.map((x,i)=>i===index?{...x,finding:event.target.value}:x)}))}/></label><label>Limite ou incerteza<textarea value={e.limit} maxLength={650} placeholder="O que este dado ainda não permite concluir?" onChange={event=>setDraft(old=>({...old,evidence:old.evidence.map((x,i)=>i===index?{...x,limit:event.target.value}:x)}))}/></label><label>Link da fonte primária<input type="url" value={e.url} maxLength={500} placeholder="https://..." onChange={event=>setDraft(old=>({...old,evidence:old.evidence.map((x,i)=>i===index?{...x,url:event.target.value}:x)}))}/></label>{index>=3&&<button className="text-button" onClick={()=>setDraft(old=>({...old,evidence:old.evidence.filter((_,i)=>i!==index)}))}><Trash2 size={14}/> Remover</button>}</fieldset>)}{draft.evidence.length<6&&<button className="button outline add-evidence" onClick={()=>setDraft(old=>({...old,evidence:[...old.evidence,blankEvidence()]}))}><Plus size={16}/> Adicionar evidência</button>}</article>
 <article className="mission-card"><span className="mission-number">03</span><div><h3>Extração</h3><p>Descreva acesso, captura, separação e o que será medido.</p></div><label className="wide">Operação proposta<textarea value={draft.extraction} maxLength={1800} placeholder="Como a equipe acessa a camada, recupera água, controla coextraídos e valida a recuperação?" onChange={e=>update('extraction',e.target.value)}/></label><aside><FileText size={18}/><strong>Premissas atuais</strong><span>{scenario.concentration}% gelo · {scenario.depth} cm cobertura · {scenario.recovery}% captura · {scenario.separation}% separação</span><span>{result.feed.toLocaleString('pt-BR',{maximumFractionDigits:0})} kg alimentados · {result.energy.toLocaleString('pt-BR',{maximumFractionDigits:0})} kWh parciais</span></aside></article>
 <article className="mission-card"><span className="mission-number">04</span><div><h3>Utilização</h3><p>Explique onde o recurso cria valor e quais requisitos o produto precisa cumprir.</p></div><label className="wide">Uso e qualificação<textarea value={draft.utilization} maxLength={1300} placeholder="Ex.: água para pesquisa, suporte à vida, oxigênio ou cadeia de propelente. Inclua os requisitos ainda não comprovados." onChange={e=>update('utilization',e.target.value)}/></label></article>
 <article className="mission-card"><span className="mission-number">05</span><div><h3>Processo de decisão e ferramentas</h3><p>Registre fontes verificadas, ferramentas usadas e informações que foram descartadas ou mantidas como hipótese.</p></div><label className="wide">Registro de verificação<textarea value={draft.decisionLog} maxLength={1800} placeholder="Ex.: quais fontes primárias foram abertas, quais dados foram conferidos, quais ferramentas ajudaram a organizar o trabalho e o que ainda precisa de confirmação." onChange={e=>update('decisionLog',e.target.value)}/></label></article>
 <div className={`mission-ready ${complete===6?'ready':''}`}>{complete===6?<><CheckCircle2 size={22}/><p>Rascunho completo para revisão da equipe. Confiram as fontes e adaptem ao limite de slides e ao pitch.</p></>:<><ClipboardCheck size={22}/><p>Complete os campos antes de usar o texto nos slides. O rascunho ajuda a organizar a decisão, não substitui a revisão das fontes.</p></>}</div></section>
}
