export type CriterionId = 'evidence' | 'access' | 'process' | 'use' | 'confidence';
export type ResourceId = 'water' | 'ilmenite' | 'pyroclastic' | 'kreep' | 'helium3';
export interface ResourceCandidate {id:ResourceId;name:string;resource:string;region:string;summary:string;value:string;limit:string;instrument:string;sourceUrl:string;sourceLabel:string;scores:Record<CriterionId,number>}
export interface ResourceSelection {resourceId:ResourceId;reason:string;updatedAt:string;scores:Record<ResourceId,Record<CriterionId,number>>}
export const RESOURCE_KEY='aqua-lunar.resource-decision.v1';
export const criteria:{id:CriterionId;name:string;question:string}[]=[
 {id:'evidence',name:'Evidência',question:'Há produtos e medições que a equipe consegue interpretar?'},
 {id:'access',name:'Acesso',question:'A região oferece uma hipótese inicial de acesso e operação?'},
 {id:'process',name:'Processo',question:'A cadeia de extração é explicável com as premissas disponíveis?'},
 {id:'use',name:'Utilização',question:'O recurso tem uso claro para a missão proposta?'},
 {id:'confidence',name:'Confiança',question:'A equipe consegue explicar limites e incertezas sem extrapolar?'},
];
export const candidates:ResourceCandidate[]=[
 {id:'water',name:'Água polar',resource:'H₂O e voláteis associados',region:'Regiões polares em sombra permanente',summary:'Hipótese de recurso para suporte à vida, oxigênio e cadeia de propelente.',value:'Pode reduzir a massa de água e gases levada da Terra para operações lunares.',limit:'Sinal de hidrogênio, temperatura ou estabilidade modelada não confirmam teor, profundidade ou recuperabilidade em um ponto.',instrument:'Diviner, LEND, LOLA e produtos polares',sourceUrl:'https://science.nasa.gov/moon/moon-water-and-ices/',sourceLabel:'NASA Science: Moon Water and Ices',scores:{evidence:4,access:2,process:3,use:5,confidence:3}},
 {id:'ilmenite',name:'Ilmenita e basaltos ricos em TiO₂',resource:'Ilmenita, ferro, titânio e oxigênio potencial',region:'Mare Tranquillitatis e porções de Oceanus Procellarum',summary:'Hipótese de uso de minerais em basaltos para oxigênio e materiais.',value:'O TiO₂ mapeado ajuda a discutir composição de mares e possíveis rotas de oxigênio.',limit:'Teor de TiO₂ não substitui caracterização local, eficiência de separação nem balanço energético da rota.',instrument:'LRO WAC, M³ e produtos mineralógicos',sourceUrl:'https://science.nasa.gov/wp-content/uploads/2023/05/NuggetLROMapTiO220180223.pdf',sourceLabel:'NASA: Mapping Minerals On the Moon',scores:{evidence:4,access:4,process:2,use:4,confidence:3}},
 {id:'pyroclastic',name:'Depósitos piroclásticos',resource:'Vidro vulcânico e voláteis a caracterizar',region:'Planalto de Aristarchus, Rima Bode e Sulpicius Gallus',summary:'Hipótese para investigar materiais vulcânicos e possíveis voláteis associados.',value:'Concentra a discussão em materiais com origem geológica distinta e aplicabilidade a processos futuros.',limit:'A presença de um depósito não informa, por si só, concentração extraível, granulometria ou rota de separação.',instrument:'M³ e mapeamento geológico',sourceUrl:'https://www.jpl.nasa.gov/missions/moon-mineralogy-mapper-m3/',sourceLabel:'JPL: Moon Mineralogy Mapper',scores:{evidence:3,access:3,process:2,use:3,confidence:2}},
 {id:'kreep',name:'Materiais do Procellarum KREEP Terrane',resource:'Potássio, elementos de terras raras e fósforo',region:'Procellarum KREEP Terrane',summary:'Hipótese para investigar elementos incompatíveis e seu valor estratégico futuro.',value:'Permite discutir materiais que podem ganhar relevância para fabricação e economia espacial.',limit:'Mapas elementares e ocorrências regionais não demonstram uma reserva concentrada, acessível ou economicamente viável.',instrument:'Lunar Prospector GRS e produtos de tório e potássio',sourceUrl:'https://pds-geosciences.wustl.edu/missions/lunarp/reduced_special.html',sourceLabel:'NASA PDS: Lunar Prospector Special Products',scores:{evidence:3,access:3,process:1,use:2,confidence:1}},
 {id:'helium3',name:'Hélio-3 no regolito',resource:'Hélio-3 associado ao regolito lunar',region:'Mares e regiões a justificar pela equipe',summary:'Hipótese frequentemente citada para uso energético futuro.',value:'Serve como alternativa para discutir dependência de tecnologia, mercado e cadeia de uso ainda não demonstrada em operação lunar.',limit:'Este projeto não usa estimativa de abundância, processo de extração ou mercado como fato estabelecido. A equipe precisa encontrar e interpretar uma fonte primária específica antes de defendê-lo.',instrument:'Dados e literatura a selecionar antes de qualquer conclusão',sourceUrl:'https://pds-geosciences.wustl.edu/missions/lunarp/',sourceLabel:'NASA PDS: Lunar Prospector',scores:{evidence:1,access:2,process:1,use:1,confidence:1}},
];
const ids=new Set(candidates.map(x=>x.id));
const valid=(x:unknown):x is Record<CriterionId,number>=>!!x&&typeof x==='object'&&criteria.every(c=>typeof (x as Record<string,unknown>)[c.id]==='number'&&Number.isInteger((x as Record<string,number>)[c.id])&&(x as Record<string,number>)[c.id]>=1&&(x as Record<string,number>)[c.id]<=5);
export function defaults():Record<ResourceId,Record<CriterionId,number>>{return Object.fromEntries(candidates.map(x=>[x.id,{...x.scores}])) as Record<ResourceId,Record<CriterionId,number>>}
export function readSelection():ResourceSelection{try{const x=JSON.parse(localStorage.getItem(RESOURCE_KEY)||'null');if(!x||!ids.has(x.resourceId)||typeof x.reason!=='string'||typeof x.updatedAt!=='string'||!x.scores||!candidates.every(c=>valid(x.scores[c.id])))throw new Error();return {resourceId:x.resourceId,reason:x.reason.slice(0,1800),updatedAt:x.updatedAt,scores:x.scores}}catch{return {resourceId:'water',reason:'',updatedAt:'',scores:defaults()}}}
export function resourceScore(scores:Record<CriterionId,number>){return criteria.reduce((sum,c)=>sum+scores[c.id],0)}
export function selectionReport(selection:ResourceSelection){const chosen=candidates.find(x=>x.id===selection.resourceId)!;return `# Comparação de recursos: ${chosen.name}\n\n## Escolha provisória\n\n${chosen.name}, na região ${chosen.region}.\n\n## Justificativa da equipe\n\n${selection.reason||'[preencher]'}\n\n## Comparação registrada\n\n${candidates.map(x=>`- ${x.name}: ${resourceScore(selection.scores[x.id])}/25. Pontuações preenchidas pela equipe, não por uma agência espacial.`).join('\n')}\n\n## Fonte inicial da escolha\n\n[${chosen.sourceLabel}](${chosen.sourceUrl})\n\n## Limite central\n\n${chosen.limit}\n\nA seleção deve ser revisada após a leitura dos produtos primários, da área escolhida e das premissas de extração.\n`;}
