import {useEffect,useMemo,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,CheckCircle2,Scale,SlidersHorizontal} from 'lucide-react';
import {candidates,criteria,defaults,readSelection,resourceScore,RESOURCE_KEY,selectionReport,type ResourceId,type ResourceSelection} from './resourceDecision';
import './resources.css';
function download(text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aqua-lunar-comparacao-recursos.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function ResourceComparator(){
 const [selection,setSelection]=useState<ResourceSelection>(readSelection);
 const sorted=useMemo(()=>[...candidates].sort((a,b)=>resourceScore(selection.scores[b.id])-resourceScore(selection.scores[a.id])),[selection.scores]);
 useEffect(()=>{try{localStorage.setItem(RESOURCE_KEY,JSON.stringify(selection))}catch{}},[selection]);
 function score(id:ResourceId,criterion:string,value:number){setSelection(old=>({...old,updatedAt:new Date().toISOString(),scores:{...old.scores,[id]:{...old.scores[id],[criterion]:value}}}))}
 const chosen=candidates.find(x=>x.id===selection.resourceId)!;
 return <section className="resource-comparator"><div className="resource-head"><div><span className="eyebrow"><Scale size={15}/> ETAPA 1 / COMPARAR ANTES DE ESCOLHER</span><h2>O que vale a pena minerar?</h2><p>Use fontes e critérios para comparar alternativas. As notas iniciais só orientam a investigação. A pontuação é da equipe, não é uma classificação da NASA.</p></div><button className="button outline" onClick={()=>download(selectionReport(selection))}><ArrowDownToLine size={16}/> Exportar comparação</button></div>
 <div className="criteria"><SlidersHorizontal size={17}/><p><strong>Critérios de 1 a 5:</strong> {criteria.map(x=>x.name.toLocaleLowerCase()).join(', ')}. Clique nas barras para registrar a avaliação da equipe. Uma nota maior indica condição mais favorável para iniciar a missão.</p></div>
 <div className="resource-summary">{sorted.map((x,index)=><button key={x.id} className={selection.resourceId===x.id?'selected':''} onClick={()=>setSelection(old=>({...old,resourceId:x.id,updatedAt:new Date().toISOString()}))}><span>{index+1}</span><strong>{x.name}</strong><b>{resourceScore(selection.scores[x.id])}<small>/25</small></b></button>)}</div>
 <section className="candidate-detail"><div className="candidate-heading"><span className="eyebrow">RECURSO EM ANÁLISE</span><h3>{chosen.name}</h3><p>{chosen.summary}</p><div><span><strong>Região de partida:</strong> {chosen.region}</span><span><strong>Instrumentos:</strong> {chosen.instrument}</span></div></div><div className="candidate-context"><h4>Valor potencial</h4><p>{chosen.value}</p><h4>O que ainda não se pode afirmar</h4><p>{chosen.limit}</p><a href={chosen.sourceUrl} target="_blank" rel="noreferrer">{chosen.sourceLabel} <ArrowUpRight size={14}/></a></div></section>
 <div className="score-table" role="group" aria-label="Pontuação dos recursos">{candidates.map(resource=><article key={resource.id} className={selection.resourceId===resource.id?'active':''}><div><h3>{resource.name}</h3><span>{resourceScore(selection.scores[resource.id])}/25</span></div>{criteria.map(c=><label key={c.id}><span>{c.name}<small>{c.question}</small></span><input aria-label={`${resource.name}: ${c.name}`} type="range" min="1" max="5" step="1" value={selection.scores[resource.id][c.id]} onChange={e=>score(resource.id,c.id,Number(e.target.value))}/><output>{selection.scores[resource.id][c.id]}</output></label>)}</article>)}</div>
 <section className="choice-card"><CheckCircle2 size={22}/><div><span className="eyebrow">ESCOLHA PROVISÓRIA</span><h3>{chosen.name}</h3><p>Escreva por que ele vence agora e por que os demais não são a primeira operação.</p></div><label>Justificativa da equipe<textarea value={selection.reason} maxLength={1800} placeholder="Compare evidência, acesso, cadeia de extração, utilização e incertezas. Cite o que ainda precisa ser comprovado." onChange={e=>setSelection(old=>({...old,reason:e.target.value,updatedAt:new Date().toISOString()}))}/></label></section>
 </section>;
}
